jenkinsci/email-ext-plugin

- src/main/java/hudson/plugins/emailext/plugins/content/JellyScriptContent.java
Allows for a jelly email create classes from plugins, like [BuildFailureAnalyzer's ScanOnDemandTask](https://github.com/jenkinsci/build-failure-analyzer-plugin/blob/master/src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandTask.java).
This is already done on the groovy-script side, so I've added it here.
> Add uberClassLoader to JellyContext

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/main/java/hudson/plugins/emailext/plugins/ContentBuilder.java
- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/config.groovy
- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global.groovy
- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/help-tokens.groovy
- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/help-tokens.properties
- src/main/resources/hudson/plugins/emailext/templates/Jive-Formatter-README.md
- src/main/resources/hudson/plugins/emailext/templates/jive-formatter.groovy
- src/main/webapp/help/globalConfig/defaultClasspath.html
- src/main/webapp/help/globalConfig/defaultPostsendScript.html
- src/main/webapp/help/globalConfig/security.html
- src/main/webapp/help/projectConfig/defaultClasspath.html
- src/main/webapp/help/projectConfig/postsendScript.html
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
- src/test/java/hudson/plugins/emailext/plugins/ContentBuilderTest.java
- src/test/java/hudson/plugins/emailext/plugins/content/TriggerNameContentTest.java
- src/test/postsend/hudson/plugins/emailext/ExtendedEmailPublisherTestHelper.groovy
- src/test/resources/recipient-provider-upgrade.xml
- src/test/resources/recipient-provider-upgrade2.xml
For some tasks pre-send scripts are not sufficient, like rewriting the Message-ID based on the SMTP response for later In-Reply-To headers. This is needed when using Amazon Simple Email Service (AWS SES) for sending emails.
Other possible use cases are scripts that act upon failed sending attempts.
Here is a example post-send script that does the message id rewriting for AWS SES:
```groovy
import com.sun.mail.smtp.SMTPTransport;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import hudson.plugins.emailext.ExtendedEmailPublisherDescriptor;
String smtpHost = props.getProperty("mail.smtp.host", "");
String awsRegex = "^email-smtp\\.([a-z0-9-]+)\\.amazonaws\\.com\$";
Pattern p = Pattern.compile(awsRegex);
Matcher m = p.matcher(smtpHost);
if (m.matches()) {
String region = …
```
> Add post-send script feature

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/plugins/content/BuildLogRegexContent.java
- src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java
- src/test/java/hudson/plugins/emailext/EmailTypeTest.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1155
- Collection.isEmpty() should be used to test for emptiness
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1155
M-Ezzat
> squid:S1155 - Collection.isEmpty() should be used to test for emptiness

- src/main/java/hudson/plugins/emailext/plugins/content/BuildLogMultilineRegexContent.java
- src/main/java/hudson/plugins/emailext/plugins/content/BuildLogRegexContent.java
- src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java
This pull request is focused on resolving occurrences of Sonar rule pmd:AppendCharacterWithChar - Append Character With Char
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=pmd:AppendCharacterWithChar
M-Ezzat
> pmd:AppendCharacterWithChar

- src/main/java/hudson/plugins/emailext/plugins/recipients/RequesterRecipientProvider.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/FailingTestSuspectsRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/FirstFailingBuildSuspectsRecipientProviderTest.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1068 - Unused private fields should be removed
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1068
M-Ezzat
> squid:S1068 - Unused private fields should be removed

- src/main/java/hudson/plugins/emailext/EmailExtTemplateAction.java
- src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java
This pull request is focused on resolving occurrences of Sonar rule pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=pmd:ConsecutiveAppendsShouldReuse
M-Ezzat
> pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/config.groovy
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
The post-send script setting disappears when saving job configuration.
This fixes up 51ab6c3 and adds a test.
References:
- https://issues.jenkins-ci.org/browse/JENKINS-33205
- Pull request #109
> Fix JENKINS-33205 (disappearing post-send script project setting)

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProvider.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2147 - Catches should be combined
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2147
M-Ezzat
> Cleanup - squid:S2147 - Catches should be combined

- src/main/java/hudson/plugins/emailext/EmailExtTemplateAction.java
- src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java
This pull request is focused on resolving occurrences of Sonar rule pmd:ConsecutiveLiteralAppends - Consecutive Literal Appends
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:ConsecutiveLiteralAppends
M-Ezzat
> Cleanup - pmd:ConsecutiveLiteralAppends - Consecutive Literal Appends

- src/main/java/hudson/plugins/emailext/plugins/trigger/XNthFailureTrigger.java
- src/main/resources/hudson/plugins/emailext/plugins/trigger/XNthFailureTrigger/help.html
- src/main/resources/hudson/plugins/emailext/plugins/trigger/XNthFailureTrigger/local-config.groovy
- src/test/java/hudson/plugins/emailext/plugins/trigger/XNthFailureTriggerTest.java
https://issues.jenkins-ci.org/browse/JENKINS-37995
> [Fix JENKINS-37995] X failure trigger

- src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java
- src/main/java/hudson/plugins/emailext/plugins/content/TestCountsContent.java
- src/main/java/hudson/plugins/emailext/plugins/content/TriggerNameContent.java
- src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java
- src/test/java/hudson/plugins/emailext/plugins/content/TestCountsContentTest.java
Added pipeline support for FAILED_TESTS, TEST_COUNTS, and TRIGGER_NAME.
> [FIXED JENKINS-38519] EMail-Ext Extended Pipeline Support - Failed Tests

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
https://issues.jenkins-ci.org/browse/JENKINS-39147
This adds setter methods to match the getters for the plugin configuration: 
- smtp auth username
- smtp auth password
- use ssl
- charset
- default content type
- default subject
- default body
- max attachment size (in bytes or Mb)
- default recipients
- excluded committers
- list id
- precedence bulk
- default reply-to
- watching
- admin
- default present script
- default post send script
There were already setters for smtp server/host, emergency reroute, default suffix, debug mode.
> [JENKINS-39147] Add API to programmatically configure global settings for email-ext plugin

- src/main/java/hudson/plugins/emailext/EmailExtStep.java
- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
This allows a pipline script to define a from address, much like the default jenkins mailer. If from is not defined, it will use the default email defined in the jenkins config.
> allow custom from address when sending email in pipeline job

- pom.xml
- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/main/java/hudson/plugins/emailext/plugins/recipients/CulpritsRecipientProvider.java
- src/main/java/hudson/plugins/emailext/plugins/recipients/DevelopersRecipientProvider.java
- src/main/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilities.java
- src/main/java/hudson/plugins/emailext/plugins/trigger/FailureTrigger.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/CulpritsRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/DevelopersRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/FailingTestSuspectsRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/FirstFailingBuildSuspectsRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/MockUtilities.java
[JENKINS-24141](https://issues.jenkins-ci.org/browse/JENKINS-24141)
Downstream of https://github.com/jenkinsci/jenkins/pull/2730 and https://github.com/jenkinsci/workflow-job-plugin/pull/35
cc @reviewbybees
> [JENKINS-24141] Switch to using RunWithSCM for getCulprits logic

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/main/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilities.java
- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global.groovy
- src/main/webapp/help/globalConfig/allowUnregistered.html
A workaround for JENKINS-43268 adding global checkbox to allow sending to unregistered emails. This is a workaround to a SCM plugin issue, like JENKINS-9016 and probably others. 
In my case, I have a ldap backed gitlab instance, and jenkins instance, where username = firstLast(and sometimes firstInitialLast) but email is first.last@company.com The git plugin appears to not like this.
> Add global checkbox to allow sending emails to unregistered users

- pom.xml
I was trying to run [Plugin Compat Tester](https://github.com/jenkinsci/plugin-compat-tester) for this plugin in order to verify it's compatibility with [JEP-200](https://github.com/jenkinsci/jep/tree/master/jep/200) changes. 
The build failed on my machine due to some failing deps, and I decided to clean it up a bit. The main change is a removal of the explicit `jenkins-war` dependency which was somehow causing HtmlUnit failures.
I also bumped the plugin to the 2.7.3 just to have the default tests running against LTS
@reviewbybees @abayer @davidvanlaatum
> Update Parent POM to 3.2 and core requirement to 2.7.3 LTS.

- src/test/java/hudson/plugins/emailext/plugins/RecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java
- src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentBuildWrapperTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/CulpritsRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/DevelopersRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/FailingTestSuspectsRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/FirstFailingBuildSuspectsRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilitiesTest.java
This PR is, hopefully, the final attempt to make the plugin build fully on Java 11.
@slide cc @jenkinsci/java11-support 
Once this succeeds, we'll want a final PR from this `java11-readiness` branch to `master`.
> Java 11 readiness

- pom.xml
Hi,
Trying to just bump the jsoup dependency over the line, so that the XSS detailed at https://www.cvedetails.com/cve/CVE-2015-6748/ is fixed.
I didn't particularly test anything, only reviewed the released notes.
Thank you.
> Bumping jsoup to get over the XSS present in <=1.8.3

- src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java
- src/main/resources/hudson/plugins/emailext/plugins/content/FailedTestsContent/help.groovy
- src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java
This PR adds flag for escaping characters in errors details and stack traces using HTML entities in `FAILED_TESTS` plugin macro token.
Examples:
```
expected:<ABORTED> but was:<COMPLETED>
at org.nexusformat.NexusFile.<clinit>(NexusFile.java:99)
```
will be replaced to:
```
expected:&lt;ABORTED&gt; but was:&lt;COMPLETED&gt;
at org.nexusformat.NexusFile.&lt;clinit&gt;(NexusFile.java:99)
```
It will be useful when content type is set to text/html.
> Added escapeHtml flag to FAILED_TESTS

- src/main/java/hudson/plugins/emailext/plugins/recipients/BuildUserRecipientProvider.java
- src/main/resources/hudson/plugins/emailext/Messages.properties
https://issues.jenkins-ci.org/browse/JENKINS-61380
When using the rebuild plugin and configuring email notifications to use the RequestorRecipientProvider, the email-ext plugin will email the original upstream build requestor and not the user who requested the rebuild.
Either RequestorRecipientProvider should take rebuilds into account somehow
or a BuildUserRecipientProvider (Maybe named differently) should be provided to notify the requestor of the current build without taking upstream causes into account.
> JENKINS-61380

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
When sending emails using the email-ext plugin, I'm manually populating the recipient list using the pre-send script feature. This means that the recipient list is empty at first and gets populated during the pre-send step.
Unfortunately an empty recipient list stops the entire process before the pre-send step is even run, with the message: "An attempt to send an e-mail to empty list of recipients, ignored".
It would make sense to let the pre-send script run before checking if the recipient list is empty.
> JENKINS-61379 - Run presend script before checking for empty recipient list

- src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java
- src/main/resources/hudson/plugins/emailext/plugins/content/FailedTestsContent/help.groovy
- src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java
Add `testSuiteName` parameter to enable `FAILED_TESTS` macro for filtering out tests of unwanted packages.
> JENKINS-62060 - Add testSuiteName parameter to filter tests of unwanted packages

- pom.xml
- src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java
- src/main/resources/hudson/plugins/emailext/plugins/content/FailedTestsContent/help.groovy
- src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java
`FAILED_TESTS` token is often used to generate emails of build failures. 
The output is currently a plain text file. It is very hard to iterate through this text file to read the failures case by case. Hence, a format easily readable and iterable would be beneficial. 
YAML is a human readable as well as machine readable format.
> Add additional parameter to `FAILED_TESTS` token to enable yaml output generation

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
Updated to check for isBlank rather than null for authentication
> Fix JENKINS-63311

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
- src/main/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTrigger.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.
> private readResolve not honored by subtypes

- pom.xml
The SpotBugs annotations are now in the plugin parent POM, so this is no longer needed.
> Remove com.google.code.findbugs:annotations from pom.xml

- pom.xml
We don't directly depend on this library, so we can remove any references to it from our `pom.xml`. As far as I can tell, it seems to have been originally added to resolve a `RequireUpperBoundDeps` violation that is no longer present.
> Remove javassist from pom.xml

- pom.xml
Can rely on the plugin parent POM and the Jenkins test harness to provide these libraries without having to maintain explicit versions of them in this plugin's POM.
> Remove explicit references to Hamcrest version

- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Not sure if this is related to failures like [#119](https://ci.jenkins.io/job/Plugins/job/email-ext-plugin/job/master/119/), but I noticed this in the logs:
```
42.990 [id=2180]	INFO	hudson.model.Run#execute: testConcurrentBuilds #1 aborted
java.lang.InterruptedException: sleep interrupted
at java.lang.Thread.sleep(Native Method)
at hudson.plugins.emailext.ExtendedEmailPublisherTest$SleepOnceBuilder.perform(ExtendedEmailPublisherTest.java:1317)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
at hudson.model.Build$BuildExecution.build(Build.java:206)
at hudson.model.Build$BuildExecution.doRun(Build.java:163)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504 …
```
> Stop build before moving on to the next test

- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherMatrixTest.java
While investigating flakiness in `ExtendedEmailPublisherMatrixTest` I noticed that this test was fairly heavyweight and could be simplified to use `@ClassRule`. This reuses the three agents for all tests rather than spawning new agents for each test.
> Rewriting ExtendedEmailPublisherMatrixTest to use ClassRule

- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherMatrixTest.java
Temporary workaround to avoid hitting infrastructure-related failures in `ExtendedEmailPublisherMatrixTest` (see #238) as I investigate code-related failures in `ExtendedEmailPublisherTest` (see #240).
> Temporarily disable ExtendedEmailPublisherMatrixTest on Windows ACI agents

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
Amends #217. Adds the `transient` keyword to `ExtendedEmailPublisherDescriptor#authenticatorProvider`, without which the following gets added to the serialized XML:
```xml
<authenticatorProvider class="hudson.plugins.emailext.ExtendedEmailPublisherDescriptor$$Lambda$131/1698888983">
<arg_-1 reference="../.."/>
</authenticatorProvider>
```
> Mark ExtendedEmailPublisherDescriptor#authenticatorProvider transient

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
A number of fields were moved from `ExtendedEmailPublisherDescriptor` to `MailAccount` at some point in the past. Most of the original getters and setters were then deprecated, but not all of them were. This change deprecates all of the original getters and setters and then updates any remaining callers to call the non-deprecated versions from `MailAccount`.
While I was here, I noticed that all references to `ExtendedEmailPublisherDescriptor#overrideGlobalSettings` were removed when JCasC support was added. This means we can drop `overrideGlobalSettings` from the serialized XML, so I've added the `transient` keyword to that field and deprecated its getter.
> Mark older fields as deprecated and migrate callers to non-deprecated equivalents

- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
- src/test/resources/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest/persistedConfigurationBeforeDefaultAddress/hudson.plugins.emailext.ExtendedEmailPublisher.xml
- src/test/resources/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest/persistedConfigurationBeforeDefaultAddress/jenkins.model.JenkinsLocationConfiguration.xml
See [JENKINS-63846](https://issues.jenkins-ci.org/browse/JENKINS-63846). This test demonstrates the problem using a serialized XML configuration from `email-ext` 2.72. Note that compared to the serialized XML configuration from `email-ext` 2.71, the bogus address has been persisted in `MailAccount#address` for the default account. Any solution to JENKINS-63846 should not only avoid this problem on clean installations, but it should also deal with this persistent state from existing installations.
> Add test demonstrating JENKINS-63846

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/main/java/hudson/plugins/emailext/MailAccount.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
See [JENKINS-63846](https://issues.jenkins-ci.org/browse/JENKINS-63846). Versions 2.71 and earlier persisted the address for additional accounts but not the default account. Starting in 2.72, the admin address is copied from the Jenkins Location configuration into the default account at the time `ExtendedEmailPublisherDescriptor` is first saved, but this value is not editable in the UI nor does it get updated when the admin address is subsequently updated in the Jenkins Location configuration. Compare the persisted XML [before](https://github.com/jenkinsci/email-ext-plugin/blob/master/src/test/resources/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest/persistedConfigurationBeforeJCasC/hudson.plugins.emailext.ExtendedEmailPublisher.xml) and …
> [JENKINS-63846] From address can't be changed

- src/main/java/hudson/plugins/emailext/plugins/content/StaticAnalysisUtilities.java
- src/main/resources/hudson/plugins/emailext/templates/static-analysis.jelly
See [JENKINS-55744](https://issues.jenkins-ci.org/browse/JENKINS-55744). The Static Analysis Utilities (`analysis-core`) plugin has been marked as end-of-life, and the relevant functionality has been integrated into the Warnings Next Generation Plugin (`warnings-ng`) plugin. At some point we will need to drop support for `analysis-core` integration from `email-ext`, ideally after `email-ext` _gains_ integration with `warnings-ng` (pull requests welcome!) to avoid dropping this functionality. This change announces the deprecation to users, directing them to the Jira issue for any further discussion. This way, there will be no surprises when it comes time to drop support for `analysis-core` integration from `email-ext`.
> Deprecate integration with analysis-core

- src/main/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProvider.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProviderTest.java
See [JENKINS-46821](https://issues.jenkins-ci.org/browse/JENKINS-46821) and its duplicate [JENKINS-59919](https://issues.jenkins-ci.org/browse/JENKINS-59919). `UpstreamComitterRecipientProvider` only considers the first upstream cause of a build, but there can be more than one upstream cause. This change updates the logic to iterate over all upstream causes in much the same way as [`RunWrapper`](https://github.com/jenkinsci/workflow-support-plugin/blob/a505b9058bbe3f357bb028bb1fd6f42c46951b35/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/RunWrapper.java#L346-L373).
> [JENKINS-46821] Upstream committer recipient provider does not consider all upstream causes

- src/test/java/hudson/plugins/emailext/AttachmentUtilsTest.java
- src/test/java/hudson/plugins/emailext/EmailExtStepTest.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherMatrixTest.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
- src/test/java/hudson/plugins/emailext/plugins/RecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/content/TriggerNameContentTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProviderTest.java
- src/test/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTriggerTest.java
- src/test/java/hudson/plugins/emailext/recipients/EmailRecipientUtilsTest.java
- Use `@Before` and `@After` methods where possible
- Name `@Before` and `@After` methods consistently
- Minimize use of `PowerMockRunner` where possible
- Remove unnecessary use of reflection where possible
> Minor test cleanup

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
See [JENKINS-63522](https://issues.jenkins-ci.org/browse/JENKINS-63522). When debug logs are enabled and the **From** address is invalid (for example, if the **System Admin e-mail address** has not been configured yet in the **Jenkins Location** section of the **Configure System** page and is still set to the default value of `nobody@nowhere`), the outer [`MessagingException`](https://javaee.github.io/javamail/docs/api/javax/mail/MessagingException.html) (typically a [`SendFailedException`](https://javaee.github.io/javamail/docs/api/javax/mail/SendFailedException.html)) is printed to the debug logs but inner exceptions (e.g., [`SMTPAddressFailedException`](https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/SMTPAddressFailedException.html), …
> [JENKINS-63522] Debug logs are incomplete when From address is invalid

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/plugins/content/ScriptContent.java
- src/main/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTrigger.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Use the `printStackTrace` methods from [`hudson.Functions`](https://javadoc.jenkins.io/hudson/Functions.html) where possible for consistency with how Jenkins prints stack traces elsewhere.
Tested that the change to line 646 of `ExtendedEmailPublisher` works by hitting the following breakpoint while running integration tests:
```
executeScript:646, ExtendedEmailPublisher (hudson.plugins.emailext)
executePresendScript:580, ExtendedEmailPublisher (hudson.plugins.emailext)
sendMail:460, ExtendedEmailPublisher (hudson.plugins.emailext)
_perform:442, ExtendedEmailPublisher (hudson.plugins.emailext)
perform:350, ExtendedEmailPublisher (hudson.plugins.emailext)
perform:20, BuildStepMonitor$1 (hudson.tasks)
perform:744, AbstractBuild$AbstractBuildExecution (hudson.model)
performAllBuildSteps:690, …
```
> Use Functions.printStackTrace where possible

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/main/java/hudson/plugins/emailext/MailAccount.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
See [JENKINS-64095](https://issues.jenkins-ci.org/browse/JENKINS-64095). #217 added more draconian enforcement of valid mail accounts. At least one user has encountered an invalid mail account and been unable to send mail. One possible area of concern is the check for `smtpUsername != null`, which would erroneously classify a mail account with an empty (not null!) SMTP username as invalid. More generally, users need a way to debug invalid mail account failures. This change adds detailed debug logs covering mail account selection and mail account validation, with which a user who encounters an invalid mail account failure can get detailed information about what is wrong with their mail account.
> Add additional debug logging when valid mail account cannot be found

- src/main/java/hudson/plugins/emailext/MailAccount.java
- src/test/java/hudson/plugins/emailext/AttachmentUtilsTest.java
- src/test/java/hudson/plugins/emailext/EmailExtStepTest.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherMatrixTest.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
- src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentSecureTest.java
- src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentTest.java
- src/test/java/hudson/plugins/emailext/plugins/content/TriggerNameContentTest.java
- src/test/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProviderTest.java
See [JENKINS-64141](https://issues.jenkins.io/browse/JENKINS-64141).
This is a very minimal change to restore a pre-2.79 behavior: having no SMTP server address (the default setting) means `localhost` will be used, which is often the right choice.
I've kept the `MailAccount.isSmtpServerValid()` method around, because it could still be a place to implement other controls (like checking that the value, if any, looks like an FQDN or IP address), but it now always returns `true`.
> [JENKINS-64141] Restore localhost as default SMTP server

- Jenkinsfile
- pom.xml
- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/main/resources/hudson/plugins/emailext/EmailExtTemplateAction/action.groovy
- src/main/resources/hudson/plugins/emailext/EmailExtTemplateAction/index.groovy
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
- Update the Jenkins baseline to 2.222.x, including updating to the latest plugin BOM.
- Depend on the `jackson2-api` plugin rather than directly on Jackson as suggested in [#229 (comment)](https://github.com/jenkinsci/email-ext-plugin/pull/229#pullrequestreview-515207359).
- Now that the baseline is 2.222.x, remove the no-longer-necessary use of reflection introduced in #208.
- Update the `Jenkinsfile` to test against the latest LTS release.
> Update Jenkins baseline, switch to jackson2-api, eliminate reflection, and test against latest LTS

- src/main/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilities.java
When attempting to email a user with a locked, disabled, or otherwise unauthorized account, different types of AuthenticationException were not caught which would cause the mail to fail.
https://issues.jenkins.io/browse/JENKINS-64629
Related to similar update in https://github.com/jenkinsci/mailer-plugin/pull/104
@jeffret-b @basil @jglick @l3ender
> [JENKINS-64629] Fix uncaught exception for unauthorized users

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- Set the SMTP port correctly using the suggested fix from https://issues.jenkins.io/browse/JENKINS-66205
> [JENKINS-66205] Correctly set SMTP port

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/plugins/content/JellyScriptContent.java
- src/main/java/hudson/plugins/emailext/plugins/content/ScriptContent.java
- src/main/java/hudson/plugins/emailext/plugins/content/TemplateContent.java
- src/test/java/hudson/plugins/emailext/AttachmentUtilsTest.java
- src/test/java/hudson/plugins/emailext/plugins/ContentBuilderTest.java
- src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentTest.java
Updates deprecated calls to methods without explicit charsets.
In addition, usage of deprecated `User.get()` replaced by `User.getById()`. Since `getById()` can return `null`, but `get()` doesn't, the test for `null` is valid now.
> Deprecated methods without charset updated

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
This checks if the from address has an @ and if not uses the defaultSuffix from the descriptor.
https://issues.jenkins.io/browse/JENKINS-63523
Hacktoberfest submission, please add the hacktoberfest-accepted label.
> fix: Use default suffix from global config with from address if only username specified

- pom.xml
- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/main/java/hudson/plugins/emailext/MailAccount.java
- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global.groovy
- src/main/resources/hudson/plugins/emailext/MailAccount/config.groovy
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorJCasCTest.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
- src/test/java/hudson/plugins/emailext/MailAccountTest.java
- src/test/resources/configuration-as-code-upgrade.yml
- src/test/resources/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest/persistedConfigurationBeforeDefaultAddress/hudson.plugins.emailext.ExtendedEmailPublisher.xml
- src/test/resources/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest/persistedConfigurationBeforeJCasC/hudson.plugins.emailext.ExtendedEmailPublisher.xml
- src/test/resources/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest/persistedConfigurationWithCredentialId/hudson.plugins.emailext.ExtendedEmailPublisher.xml
- src/test/resources/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest/persistedConfigurationWithCredentialId/jenkins.model.JenkinsLocationConfiguration.xml
This switches the MailAccount class to use credentials instead of directly storing the username/password. There is an upgrade path from the old settings to using credentials.
https://issues.jenkins.io/browse/JENKINS-66849
Hacktoberfest submission
> feat: Use credentials plugin for managing authentication credentials

- pom.xml
- src/test/java/hudson/plugins/emailext/AttachmentUtilsTest.java
I can't see a good reason to customize this.
> Remove `file.encoding` customization

- pom.xml
- src/main/java/hudson/plugins/emailext/plugins/recipients/ContributorMetadataRecipientProvider.java
- src/main/resources/hudson/plugins/emailext/Messages.properties
- src/test/java/hudson/plugins/emailext/plugins/recipients/ContributorMetadataRecipientProviderTest.java
This adds a recipient provider which pulls information from the ContributorMetadataAction which is applied to the Run from multiple SCM providers.
https://issues.jenkins.io/browse/JENKINS-62079
> fix: JENKINS-62079 - Add contributor() recipient provider which pulls information from ContributorMetadataAction

- Jenkinsfile
- pom.xml
Downstream of #335 and jenkinsci/jenkins#6165. Bumps the baseline to one containing jenkinsci/jenkins#6165, thus using the detached JavaMail plugin, but does not upgrade to Jakarta Mail.
> Use detached JavaMail plugin

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/main/java/hudson/plugins/emailext/MailAccount.java
- src/main/resources/hudson/plugins/emailext/MailAccount/config.groovy
This adds a checkbox to the mail account configuration to allow users to enable OAuth 2.0 (see https://javaee.github.io/javamail/OAuth2).
The token needs to be put as the password in the credentials.
See https://issues.jenkins.io/browse/JENKINS-69414
I tested with Gmail using my email address and the OAuth 2.0 token as the password in the credential for the MailAccount.
> fix: JENKINS-69414 - Add OAuth 2.0 support

- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/help-tokens.properties
This is related to https://issues.jenkins.io/browse/JENKINS-69750, where a user thought they could specify a full path to a file rather than a workspace relative path. This updates the example to hopefully have that not happen in the future.
> doc: Update to not show specific directory path

- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
Jenkins 2.395 includes https://github.com/jenkinsci/jenkins/pull/7661 that simplifies the names of the settings on the "Configure System" page.
That simplification breaks email-ext tests in the Jenkins plugin bill of materials and any time they are run with Jenkins 2.395 or later.  We can temporarily exclude the tests from the plugin bill of materials, but it is much better to have the tests pass.
This pull request adapts the tests to the change so that they pass with the current weekly and past LTS releases.
https://github.com/jenkinsci/bom/pull/1857 shows the failing tests with Jenkins 2.395.
The failures can also be seen with the command:
```
$ mvn clean -Djenkins.verison=2.395 -Dtest=ExtendedEmailPublisherDescriptorTest verify
```
> Fix tests with Jenkins 2.395

- pom.xml
Since [2.361.x](https://github.com/jenkinsci/bom/pull/2121) and [2.375.x](https://github.com/jenkinsci/bom/pull/2218) support was dropped it makes sense to upgrade towards 2.387.x
Had to jump directly to 2.387.3 as `jenkins.version` since a transitive dependency to `font-awesome-api` (among others) requires it.
Validated changes via `mvn clean verify`
```[tasklist]
```
> Upgrade to 2.387.x

- src/main/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilities.java
[JENKINS-71709](https://issues.jenkins.io/browse/JENKINS-71709): log not just the user email address but also user ID to help identify why a user might be subjected to a specific warning (such as missing permission).
Let me know if a test is needed for this.
```[tasklist]
```
> [JENKINS-71709] Improve logger message to identify users by ID

- src/main/resources/hudson/plugins/emailext/templates/groovy-html-larry.template
- src/main/resources/hudson/plugins/emailext/templates/groovy-html.template
The email was not coming in the default expected template format as Gmail no longer supports the Style tag.
Done
```[tasklist]
```
> HTML formatted email not showing up at all in Gmail 

- src/test/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTriggerTest.java
Amending 04efc239ca882a411414ebadc6785bc21aa0910f by @rsandell. Clearer here to use methods which are clearly not destined for a whitelist.
> Avoid relying on `Run.getResult` in `AbstractScriptTriggerTest.configRoundtrip`

- src/main/resources/hudson/plugins/emailext/templates/groovy-html.template
- src/main/resources/hudson/plugins/emailext/templates/groovy-text.template
- src/main/resources/hudson/plugins/emailext/templates/html.jelly
- src/main/resources/hudson/plugins/emailext/templates/text.jelly
From personal experience I think it makes sense to include the reports from [warnings-ng](https://github.com/jenkinsci/warnings-ng-plugin) in the emails send by Jenkins. I know that one can customize the templates as desired but I'd love to see this added as a _recommendation_.
I added the reports only to the currently documented templates and left the other untouched.
Regarding the code-formatting: It is a mess already and I did not bother - let me know if you want me to change it.
See the screenshots below that demonstrate the feature:
**groovy-html.template**
**groovy-text.template**
**html.jelly**
**text.jelly**
Existing tests run fine. Manually tested visual changes are as intended - see screenshots for details.
```[tasklist]
```
> Include warnings-ng reports in templates

- pom.xml
- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/MailAccount.java
- src/test/java/hudson/plugins/emailext/FormValidationMessageMatcher.java
- src/test/java/hudson/plugins/emailext/MailAccountFIPSTest.java
As SMTP is plain text, any credential used can be leaked on the network. Due to this issue a warning when using a credential without using TLS or SSL.
Additionally when in FIPS mode this becomes a hard requirement, so the warning becomes and error and the `MailAccount` will be treated as invalid
analogous to https://github.com/jenkinsci/mailer-plugin/pull/275
see new unit tests
```[tasklist]
```
> [JENKINS-72912] Warn when using authentication without encryption

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
- src/test/java/hudson/plugins/emailext/plugins/ContentBuilderTest.java
Addresses what seems to have been a regression from 04efc23: every time you save the global config page, a warning pops up in **Manage** that you have a script to approve…but it is empty. Note that the method call here is deprecated as of https://github.com/jenkinsci/script-security-plugin/commit/f4c0bb9b58e105b4fc6b62be0f7f2daa46178190 but I am not touching that.
> Do not submit an empty pre/post-send script for approval

- src/main/resources/hudson/plugins/emailext/EmailExtTemplateAction/index.groovy
- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/config.groovy
- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global.groovy
remove fetching the field value via javascript and set the checkDependsOn attribute. This avoids that core interprets the code as javascript and calls eval on the url which is a violation of CSP rules.
Manual testing by visiting the corresponding pages and entering invalid data. Validation error is still shown.
With CSP plugin installed there is nothing reported anymore.
> remove inline js from checkUrl

- pom.xml
- src/main/java/hudson/plugins/emailext/MailAccount.java
- src/test/java/hudson/plugins/emailext/MailAccountFIPSTest.java
- src/test/java/hudson/plugins/emailext/MailAccountTest.java
Signed-off-by: Olivier Lamy <olamy@apache.org>
> Adapt to changes from credentials regarding password length in FIPS mode https://github.com/jenkinsci/credentials-plugin/pull/558

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
- src/main/java/hudson/plugins/emailext/plugins/EmailTrigger.java
- src/main/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTrigger.java
- src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java
- src/main/java/hudson/plugins/emailext/watching/EmailExtWatchJobProperty.java
- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Replace usages of deprecated types with non-deprecated equivalents. Checked by grepping in sources that nothing outside of this plugin calls the methods whose signatures have changed.
`mvn clean verify`
> Migrate to Jakarta EE 9

- src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
- src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java
- src/main/java/hudson/plugins/emailext/watching/EmailExtWatchJobProperty.java
- src/main/resources/hudson/plugins/emailext/watching/EmailExtWatchAction/index.groovy
Fixes the watching feature so that when a user watches a given job, it only applies to that job. Previously, when a job was watched, the project was not stored in the user property, so it would end up watching all jobs.
> fix: prevent watching from applying to all jobs

- src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java
- src/test/java/hudson/plugins/emailext/EmailRecipientUtilsTest.java
Updated the delimiter fix-up to take into account personal names in email addresses (e.g., `Slide O Mix <someone@email.com>`).
See [JENKINS-69681](https://issues.jenkins.io/browse/JENKINS-69681)
Supersedes #395
> fix: Update delimiter fix-up for personal parts

- src/main/resources/hudson/plugins/emailext/EmailExtTemplateAction/index.groovy
- src/main/resources/hudson/plugins/emailext/EmailExtTemplateAction/template-test.js
https://issues.jenkins.io/browse/JENKINS-74891
There's still a problem with the mechanism that renders the template. It's rendered inside an `iframe` element. Default CSP header that's set by [Content Security Policy](https://plugins.jenkins.io/csp/) does not define `frame-src`, hence `default-src` is used, which only allows `'self'`. This means that `data:` src for `iframe` is not allowed, which prohibits templates from being rendered in restrictive mode. This is also be demonstrated on "After the change" video below.
Depending on how wanted this feature is it can either be fixed or deprecated with a notice that it doesn't work in CSP restrictive mode. 
Alternatively CSP plugin could define `frame-src` policy that we'd consider safe (probably a question to @jenkinsci/core-security-review …
> [JENKINS-74891] Extract inline JavaScript from `EmailExtTemplateAction/index.groovy`

- src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
https://github.com/jenkinsci/jenkins/pull/10178 changes the format of the page title, going from `x [Jenkins]` to `x - Jenkins`. As a result it's broken one of the tests in this plugin, this PR resolves that whilst maintaining backwards compatibility with older versions of Jenkins.
* Tests pass
> Fix page title test for new title format

- src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java
Spotless seems to generate different results when running on Windows agents of ci.jenkins.io and Linux agents of ci.jenkins.io.
This avoids the difference by moving the comment into a section where Windows and Linux formatting does not result in a difference.  This will fix the build on the main branch @slide .
Ran `mvn spotless:apply` on Linux.  Rely on ci.jenkins.io to test both Windows and Linux.
> Move comment to fix spotless formatting

- src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/config.groovy
Fix for https://issues.jenkins.io/browse/JENKINS-75845
Sorry I introduced a regression while working on https://github.com/jenkinsci/email-ext-plugin/pull/618.
Tested manually:
> [JENKINS-75845] Fix select name for Attach Build Log
