src/main/java/hudson/plugins/emailext/plugins/content/UnevaluatedScriptContent.java, src/main/resources/hudson/plugins/emailext/plugins/content/UnevaluatedScriptContent/help.groovy, src/test/java/hudson/plugins/emailext/plugins/content/UnevaluatedScriptContentTest.java
Allow for presend scripts to be legoed together like an email's body is.
Now with 94.3% less weirdness.
=> Add SCRIPT_CONTENT TokenMacro

src/main/java/hudson/plugins/emailext/EmailExtTemplateActionFactory.java
Basically f56bf85320cc1b2f6089b117efc70b595a115593 again.
@reviewbybees
=> [JENKINS-25940] Add workaround to prevent NPE in Maven projects

src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java, src/main/java/hudson/plugins/emailext/plugins/content/AbstractChangesSinceContent.java, src/main/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilities.java, src/main/java/hudson/plugins/emailext/plugins/recipients/RequesterRecipientProvider.java, src/main/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProvider.java, src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java, src/main/java/hudson/plugins/emailext/watching/EmailExtWatchJobProperty.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2208 - Wildcard imports should not be used
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2208
M-Ezzat
=> squid:S2208 - Wildcard imports should not be used

src/main/java/hudson/plugins/emailext/AttachmentUtils.java, src/main/java/hudson/plugins/emailext/EmailExtTemplateAction.java, src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java, src/main/java/hudson/plugins/emailext/EmailType.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java, src/main/java/hudson/plugins/emailext/plugins/ContentBuilder.java, src/main/java/hudson/plugins/emailext/plugins/EmailTrigger.java, src/main/java/hudson/plugins/emailext/plugins/EmailTriggerDescriptor.java, src/main/java/hudson/plugins/emailext/plugins/content/EmailExtScript.java, src/main/java/hudson/plugins/emailext/plugins/content/ScriptContent.java, src/main/java/hudson/plugins/emailext/plugins/content/ScriptContentBuildWrapper.java, src/main/java/hudson/plugins/emailext/plugins/content/StaticAnalysisUtilities.java, src/main/java/hudson/plugins/emailext/plugins/recipients/DevelopersRecipientProvider.java, src/main/java/hudson/plugins/emailext/plugins/recipients/FailingTestSuspectsRecipientProvider.java, src/main/java/hudson/plugins/emailext/plugins/recipients/FirstFailingBuildSuspectsRecipientProvider.java, src/main/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilities.java, src/main/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProvider.java, src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java, src/main/java/hudson/plugins/emailext/watching/EmailExtWatchJobProperty.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2293 - The diamond operator should be used
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2293
M-Ezzat
=> squid:S2293 - The diamond operator should be used

src/main/java/hudson/plugins/emailext/plugins/trigger/XNthFailureTrigger.java, src/main/resources/hudson/plugins/emailext/plugins/trigger/XNthFailureTrigger/local-config.groovy, src/test/java/hudson/plugins/emailext/plugins/trigger/XNthFailureTriggerJTest.java
Missed it because got false positive testing result from other person
=> [JENKINS-37995] Fix getter value in UI

pom.xml, src/main/resources/index.jelly
[JENKINS-42244](https://issues.jenkins-ci.org/browse/JENKINS-42244)
@reviewbybees @davidvanlaatum
=> [JENKINS-42244] Change description according to Wiki

src/main/java/hudson/plugins/emailext/plugins/recipients/CulpritsRecipientProvider.java
=> [FIXED JENKINS-42761]

src/main/resources/hudson/plugins/emailext/templates/groovy-html.template
Fixes wrong variable name in template
which was failing rendering of template.
JENKINS-38968
=> Correct use of build.changeSets

src/main/resources/hudson/plugins/emailext/templates/groovy-html.template, src/main/resources/hudson/plugins/emailext/templates/groovy-text.template
Fixed the bug for the text template, the original patch fixed only the HTML one.
=> Jenkins 46818 msg for text template

src/main/resources/hudson/plugins/emailext/templates/groovy-html.template
Sample of success:
Sample of failure:
=> Styling changes + change in test results table + code alignment

pom.xml, src/main/java/hudson/plugins/emailext/plugins/CssInliner.java, src/test/java/hudson/plugins/emailext/plugins/CssInlinerTest.java
JSoup has some clean-up in a more recent version and some additional cleanup in the newer token macro as well that make some things easier. This updated the libraries and tests.
=> Update some libraries for some feature additions.

src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java, src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global.groovy, src/main/webapp/help/globalConfig/allowedDomains.html, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
This implements domain filter where we specify all alowed domains. prior
to sending email we check if destination address is on white list. if
not then email address is removed from the list.
=> allow filtering email domains we send emails to

src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java, src/main/java/hudson/plugins/emailext/RecipientListStringAnalyser.java, src/test/java/hudson/plugins/emailext/RecipientListStringAnalyserTest.java, src/test/java/hudson/plugins/emailext/recipients/EmailRecipientUtilsTest.java
This PR addresses https://issues.jenkins-ci.org/browse/JENKINS-52748
=> JENKINS-52748: Same recipient in CC or BCC removes it from TO

src/main/java/hudson/plugins/emailext/plugins/content/EmailExtScript.java, src/main/java/hudson/plugins/emailext/plugins/content/ScriptContent.java
Allow pipeline to use tokens in groovy templates. Previously, this was expecting AbstractBuild's.
=> Support pipeline for using tokens

Jenkinsfile, pom.xml, src/test/java/hudson/plugins/emailext/plugins/recipients/MockUtilities.java
Using pom `3.32` and recommended version for powermock solve the problem.
@jenkinsci/java11-support @davidvanlaatum
=> [JENKINS-55233] Make sure to use latest pom and recommend lib versions

src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global.groovy, src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global_zh_TW.properties
Trivial change, but it's referred to as E-mail in the rest of the plugin.
=> Email -> E-mail in config page

Jenkinsfile, pom.xml, src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java, src/main/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilities.java, src/test/java/hudson/plugins/emailext/plugins/RecipientProviderTest.java, src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java, src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentBuildWrapperTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/CulpritsRecipientProviderTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/DevelopersRecipientProviderTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/FailingTestSuspectsRecipientProviderTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/FirstFailingBuildSuspectsRecipientProviderTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilitiesTest.java
#180 and #179 , just another attempt to confuse CI even more
=> Java11 readiness

src/main/java/hudson/plugins/emailext/EmailExtStep.java, src/test/java/hudson/plugins/emailext/EmailExtStepTest.java
See [JENKINS-56794](https://issues.jenkins-ci.org/browse/JENKINS-56794)
See https://groups.google.com/forum/#!topic/jenkinsci-users/sk1jroBxNbo
=> [JENKINS-56794] Support saveOutput parameter in the pipeline step

pom.xml, src/main/java/hudson/plugins/emailext/plugins/content/AbstractEvalContent.java, src/main/java/hudson/plugins/emailext/plugins/content/JellyScriptContent.java, src/main/java/hudson/plugins/emailext/plugins/content/ScriptContent.java, src/main/java/hudson/plugins/emailext/plugins/content/TemplateContent.java, src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentTest.java, src/test/resources/hudson/plugins/emailext/plugins/content/ScriptContentTest/testTemplateShouldBeLoadedFromTheClosestExistingFolderConfigInTheHierarchyUpToGlobalConfig/jobs/parent-folder/config.xml, src/test/resources/hudson/plugins/emailext/plugins/content/ScriptContentTest/testTemplateShouldBeLoadedFromTheClosestExistingFolderConfigInTheHierarchyUpToGlobalConfig/jobs/parent-folder/jobs/test-folder/config.xml, src/test/resources/hudson/plugins/emailext/plugins/content/ScriptContentTest/testTemplateShouldBeLoadedFromTheClosestExistingFolderConfigInTheHierarchyUpToGlobalConfig/org.jenkinsci.plugins.configfiles.GlobalConfigFiles.xml
Fix of [JENKINS-60911](https://issues.jenkins-ci.org/browse/JENKINS-60911) issue.
=> [JENKINS-60911] Make files (template, script, etc...) correctly loaded through config-file-provider-plugin when defined at folder level

src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
Move to an initializer after extensions have been augmented
=> Fix JENKINS-60002

src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorJCasCTest.java, src/test/resources/configuration-as-code-with-triggers.yml
=> Validate triggers configuration with casc

.gitignore, Jenkinsfile, pom.xml, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java, src/main/java/hudson/plugins/emailext/MailAccount.java, src/main/java/hudson/plugins/emailext/plugins/CssInliner.java, src/main/java/hudson/plugins/emailext/plugins/recipients/BuildUserRecipientProvider.java, src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global.groovy, src/main/resources/hudson/plugins/emailext/GroovyScriptPath/config.groovy, src/main/resources/hudson/plugins/emailext/MailAccount/config.groovy, src/main/resources/hudson/plugins/emailext/Messages.properties, src/main/webapp/help/globalConfig/maxAttachmentSize.html, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorJCasCTest.java, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java, src/test/resources/configuration-as-code.yml
This updates email-ext to be compliant with the JCaSC plugin and includes a test for support. Thanks to @alecharp for his help!
=> Fix JENKINS-62444

src/main/java/hudson/plugins/emailext/MailAccount.java, src/main/resources/hudson/plugins/emailext/MailAccount/config.groovy, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
- Used "default" instead of "value" in the form element
- Added test for this specific issue
=> Fix JENKINS-63367

src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
=> Fix negation (JENKINS-63311)

src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java, src/test/java/hudson/plugins/emailext/AttachmentUtilsTest.java, src/test/java/hudson/plugins/emailext/EmailExtStepTest.java, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherMatrixTest.java, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java, src/test/java/hudson/plugins/emailext/MailAccountTest.java, src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java, src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentSecureTest.java, src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentTest.java, src/test/java/hudson/plugins/emailext/plugins/content/TriggerNameContentTest.java
=> Authentication tests

pom.xml
Release Notes:
- [jackson-dataformats-text](https://github.com/FasterXML/jackson-dataformats-text/blob/master/release-notes/VERSION-2.x)
- [jackson-databind](https://github.com/FasterXML/jackson-databind/blob/master/release-notes/VERSION-2.x)
=> Update jackson to 2.10.5

src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Adds missing test coverage for the "Project From" feature.
=> Add test for Project From

src/main/java/hudson/plugins/emailext/EmailExtRecipientStep.java, src/main/java/hudson/plugins/emailext/EmailExtStep.java, src/test/java/hudson/plugins/emailext/EmailExtStepTest.java
Replacing usages of deprecated classes with their non-deprecated equivalents.
=> Removing usages of Guice

src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
as suggested by @jglick in https://github.com/jenkinsci/email-ext-plugin/pull/212#discussion_r551444817
=> add backwards compatible symbol

pom.xml
Moves the past maintainers out of the current maintainers area
=> chore: Move past maintainers to the contributors area

pom.xml, src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java, src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentBuildWrapperTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/CulpritsRecipientProviderTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/DevelopersRecipientProviderTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/FailingTestSuspectsRecipientProviderTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/FirstFailingBuildSuspectsRecipientProviderTest.java, src/test/java/hudson/plugins/emailext/plugins/recipients/MockUtilities.java, src/test/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilitiesTest.java
Amends #310. Adapts to jenkinsci/plugin-pom#442.
=> Remove PowerMock

pom.xml
Get these from the BOM instead.
=> Remove hard-coded dependencies

src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
see https://github.com/jenkinsci/jenkins/pull/7173#issuecomment-1368056507
This is forward and backwards compatible
=> Adapt test to advanced component change in core

pom.xml, src/main/java/hudson/plugins/emailext/EmailExtTemplateAction.java, src/main/java/hudson/plugins/emailext/groovy/sandbox/SimpleTemplateEngine.java, src/main/java/hudson/plugins/emailext/plugins/content/AbstractEvalContent.java, src/main/java/hudson/plugins/emailext/plugins/content/ScriptContent.java, src/main/resources/hudson/plugins/emailext/EmailExtTemplateAction/index.groovy, src/main/resources/hudson/plugins/emailext/templates/groovy-html-larry.template, src/main/resources/hudson/plugins/emailext/templates/groovy-html.template, src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentSecureTest.java
[Security advisory](https://www.jenkins.io/security/advisory/2023-02-15/)
The branch histories have diverged during the staging period.
This PR should be merged using merge-commit, not using squash-commit or rebase-commit, to ensure the commits related to the release are in the history of the default branch.
=> Integrate 2023-02-15 security fixes into default branch

pom.xml
Updates required minimum version of Jenkins to be 2.440.3
=> Update pom.xml for Jenkins version 2.440.3

pom.xml
Update minimum Jenkins version to pull in updates in other plugins that require it.
=> Update minimum Jenkins version

src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java, src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global.groovy, src/main/webapp/help/globalConfig/throttlingEnabled.html, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Add global configuration to disable throttling.
Added unit test with throttling disabled to show that disabling throttling would allow all emails through.
https://issues.jenkins.io/browse/JENKINS-73740
=> JENKINS-73740: Allow admins to disable throttling

pom.xml, src/main/java/hudson/plugins/emailext/AttachmentUtils.java, src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherContext.java, src/main/java/hudson/plugins/emailext/MailAccount.java, src/main/java/hudson/plugins/emailext/groovy/sandbox/EmailExtScriptTokenMacroWhitelist.java, src/main/java/hudson/plugins/emailext/plugins/EmailTrigger.java, src/main/java/hudson/plugins/emailext/plugins/EmailTriggerDescriptor.java, src/main/java/hudson/plugins/emailext/plugins/content/AbstractEvalContent.java, src/main/java/hudson/plugins/emailext/plugins/content/EmailExtScript.java, src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java, src/main/java/hudson/plugins/emailext/plugins/content/ScriptContentBuildWrapper.java, src/main/java/hudson/plugins/emailext/plugins/recipients/CulpritsRecipientProvider.java, src/main/java/hudson/plugins/emailext/plugins/recipients/PreviousRecipientProvider.java, src/main/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilities.java, src/main/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProvider.java, src/main/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTrigger.java, src/main/java/hudson/plugins/emailext/plugins/trigger/PreBuildScriptTrigger.java, src/main/java/hudson/plugins/emailext/plugins/trigger/ScriptTrigger.java, src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java, src/test/java/hudson/plugins/emailext/AttachmentUtilsTest.java, src/test/java/hudson/plugins/emailext/EmailExtStepTest.java, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java, src/test/java/hudson/plugins/emailext/plugins/CssInlinerTest.java, src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java, src/test/java/hudson/plugins/emailext/plugins/content/JellyScriptContentTest.java, src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentSecureTest.java, src/test/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTriggerTest.java
Updates plugin to LTS that requires Java 17. Applied using OpenRewrite Java11to17 plugin which updates to use instanceof pattern matching instead of casting.
=> Require Java 17

.github/workflows/jenkins-security-scan.yml, CHANGELOG.adoc, README.adoc, docs/recipes.adoc, docs/templates/jenkins-generic-matrix-email-html.template, docs/templates/jenkins-matrix-email-html.template, src/main/java/hudson/plugins/emailext/GroovyScriptPath.java, src/main/resources/hudson/plugins/emailext/templates/html-with-health-and-console.jelly, src/main/resources/hudson/plugins/emailext/templates/static-analysis.jelly
Cleans up some items that needed to be updated after changing the default branch from master to main.
=> Clean-up items after "master" to "main" change

src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java
Fixes issue where the user property may have a null project name.
=> fix: Fix-up NullPointerException

pom.xml
Will avoid jar duplication and possible classpath issue
mvn clean install
=> Use jsoup api plugin instead of direct dependency

src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java
Fix spotless issue that shows up with newer parent pom version.
=> Fix spotless issue

src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java, src/main/java/hudson/plugins/emailext/plugins/EmailTrigger.java, src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/config.groovy, src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
[JENKINS-75797](https://issues.jenkins.io/browse/JENKINS-75797)
Hello,
Due to internal automation and tooling at CloudBees, I would like to apply a few minor refactoring:
- rename the parameter of the [ExtendedEmailPublisher](https://github.com/jenkinsci/email-ext-plugin/blob/76e30f9ec03b2b70a1053fa1bb2ec44b284be6c4/src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java#L211-L222) data-bound constructor to align the parameter names with the field names;
- add a few getters in EmailTrigger and ExtendedEmailPublisher
If this is approved, I will also update the [Acceptance Test Harness.](https://github.com/jenkinsci/acceptance-test-harness/blob/0ffc0aa9f5f16d59571409ddd0510ae234b1734f/src/main/java/org/jenkinsci/test/acceptance/plugins/email_ext/EmailExtPublisher.java)
Thanks
=> [JENKINS-75797] Minor refactoring

pom.xml
This library is now published to Maven Central under a new group ID.
CI build
=> Upgrade Mock JavaMail from 2.2 to 2.3

pom.xml, src/main/java/hudson/plugins/emailext/AttachmentUtils.java, src/main/java/hudson/plugins/emailext/EmailExtStep.java, src/main/java/hudson/plugins/emailext/EmailExtTemplateAction.java, src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java, src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java, src/main/java/hudson/plugins/emailext/MailAccount.java, src/main/java/hudson/plugins/emailext/plugins/ContentBuilder.java, src/main/java/hudson/plugins/emailext/plugins/CssInliner.java, src/main/java/hudson/plugins/emailext/plugins/RecipientProvider.java, src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java, src/main/java/hudson/plugins/emailext/plugins/content/ScriptContent.java, src/main/java/hudson/plugins/emailext/plugins/content/TemplateContent.java, src/main/java/hudson/plugins/emailext/plugins/recipients/ContributorMetadataRecipientProvider.java, src/main/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTrigger.java, src/main/resources/hudson/plugins/emailext/templates/groovy-html.template, src/test/java/hudson/plugins/emailext/EmailExtStepTest.java, src/test/java/hudson/plugins/emailext/plugins/ContentBuilderTest.java, src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java
Migrate from deprecated/EOL Commons Lang 2 to Commons Lang 3.
=> Upgrade Commons Lang from 2 to 3
